import { AlertTriangle, Pill, Activity, Users, ClipboardList, Siren, Sparkles, type LucideIcon } from "lucide-react";
import { useHaven, type Notification, type Role } from "@/lib/haven-store";
import { Button } from "@/components/ui/button";

const icons: Record<string, LucideIcon> = {
  Pill, Activity, AlertTriangle, Users, ClipboardList, Siren,
};

const sevStyle: Record<Notification["severity"], string> = {
  info: "border-l-haven-teal bg-haven-teal/5",
  warning: "border-l-haven-warning bg-haven-warning/5",
  danger: "border-l-haven-danger bg-haven-danger/5",
};

const sevBadge: Record<Notification["severity"], string> = {
  info: "bg-haven-teal/20 text-haven-navy",
  warning: "bg-haven-warning/30 text-haven-navy",
  danger: "bg-haven-danger text-white",
};

export function NotificationList({ role, large = false }: { role: Role; large?: boolean }) {
  const notes = useHaven((s) => s.notifications).filter((n) => n.audience === role || n.audience === "all");
  if (notes.length === 0) {
    return (
      <div className="haven-card grid place-items-center p-12 text-center text-muted-foreground">
        <p className={large ? "text-2xl" : "text-base"}>No notifications. Start the demo to see updates.</p>
      </div>
    );
  }
  return (
    <div className="space-y-4">
      {notes.slice().reverse().map((n) => {
        const Icon = icons[n.icon] ?? AlertTriangle;
        return (
          <div key={n.id} className={`haven-card animate-slide-up border-l-4 p-5 ${sevStyle[n.severity]}`}>
            <div className="flex items-start gap-4">
              <div className={`grid place-items-center rounded-lg p-2.5 ${sevBadge[n.severity]}`}>
                <Icon className={large ? "h-8 w-8" : "h-5 w-5"} />
              </div>
              <div className="flex-1">
                <div className="flex flex-wrap items-center gap-2">
                  <h3 className={`font-semibold text-haven-navy ${large ? "text-2xl" : "text-base"}`}>{n.title}</h3>
                  <span className={`rounded-full px-2 py-0.5 text-xs font-semibold uppercase ${sevBadge[n.severity]}`}>{n.severity}</span>
                  <span className={`text-muted-foreground ${large ? "text-base" : "text-xs"}`}>{n.time}</span>
                </div>
                <p className={`mt-2 text-haven-navy/80 ${large ? "text-xl leading-relaxed" : "text-sm"}`}>{n.body}</p>
                {n.actions && (
                  <div className="mt-3 flex flex-wrap gap-2">
                    {n.actions.map((a, i) => (
                      <Button key={a} size={large ? "lg" : "sm"} variant={i === 0 ? "default" : "outline"} className={i === 0 ? "bg-haven-navy text-haven-warm hover:bg-haven-navy-deep" : ""}>
                        {a}
                      </Button>
                    ))}
                  </div>
                )}
                {n.aiGenerated && (
                  <p className="mt-3 flex items-center gap-1 text-xs text-muted-foreground">
                    <Sparkles className="h-3 w-3" /> Generated by Haven AI
                  </p>
                )}
              </div>
            </div>
          </div>
        );
      })}
    </div>
  );
}